server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://localhost:8183/elastic-query-service/documents'
    # service-id: elastic-query-service
    # instances:
    #   -
    #     id: elastic-query-service-1
    #     host: localhost
    #     port: 8183
    #   -
    #     id: elastic-query-service-2
    #     host: localhost
    #     port: 8185
  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client'
            client-secret: '{cipher}beebbeea9c45da8176053d75b3bc439c840dbddf567e84a3cce659bf7daa9cf49af26e1f2a20ac38527cea55118af33e3021b5b37efd6730ad35041d03b1528e'
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:9091/auth/realms/microservices-realm


security:
  logout-success-url: http://localhost:8184/elastic-query-web-client
  default-client-registration-id: keycloak

user-config:
  username: test
  password: '{cipher}baeb90d57edb9a050b97b98a7d8cabe80ee884e6fff16c22956172459a43e54d'
  roles: USER
